# Assignment 2 - Numpy

*This assignment is a part of the course ["Data Analysis with Python: Zero to Pandas"](https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas)*

# GET TO KNOW ABOUT 5 NUMPY OPERATIONS

Numpy is a python library that is used to handle arrays very efficiently. Numpy makes it easier to handle large datasets easily and in a faster way using its built-in functions. 

- numpy.roll
- numpy.unique
- numpy.arcsin , numpy.arccos, numpy.arctan
- numpy.nanmax
- numpy.isnan



Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.roll
function2 = np.unique
function3 = np.arcsin , np.arccos, np.arctan
function4 = np.nanmax
function5 = np.isnan

## Function 1 - numpy.roll

Using np.roll() we can roll the elements along a given axis

In [6]:
a = np.arange(7,30,3)
a

array([ 7, 10, 13, 16, 19, 22, 25, 28])

In [7]:
#Example 1

np.roll(a,3)

array([22, 25, 28,  7, 10, 13, 16, 19])

We passed "a" array and 3 as parameters. The roll function right shifts the elements in the array by 3 and returns the output.

In [8]:
# Example 2

arr = np.reshape(a,(2,4))
print(arr)
print("Array after rolling: ")

np.roll(arr,-1,axis=1)

[[ 7 10 13 16]
 [19 22 25 28]]
Array after rolling: 


array([[10, 13, 16,  7],
       [22, 25, 28, 19]])

 Now we have mentioned the axis = 1 while passing arguments. This rolls the element by 1 index along the axis-1 i.e. horizontal axis. <br> <br>
NOTE: <br>
1.If axis not specified axis is set to NONE<br>
2. Also the original array is not modified when we perform the roll operation on any array  


In [9]:
# Example 3 

np.roll(arr,3,axis=3)

AxisError: axis 3 is out of bounds for array of dimension 2

In the above example the axis = 3, as this was a 2D array it has only 2 axis so we get an error.

The roll() function would be really helpful if we want to arrange the elements in the array to see the bottom elements to be see first.

## Function 2 - numpy.unique

This function returns the unique elements in the array ignoring the dupicates present in it.

In [11]:
# Example 1 

ar = np.array([[1,7,25,1],
               [25,4,3,25],
               [1,7,25,1],
               [2,4,1,2]])
ar1 = np.unique(ar,axis=1)
ar1

array([[ 1,  7, 25],
       [25,  4,  3],
       [ 1,  7, 25],
       [ 2,  4,  1]])

This functions returns the unique element along the axis - 1 and ignores the duplicates.

In [12]:
# Example 2 

ar2, count = np.unique(ar,axis=0, return_counts = True)
ar2

array([[ 1,  7, 25,  1],
       [ 2,  4,  1,  2],
       [25,  4,  3, 25]])

In [13]:
count

array([2, 1, 1])

In the above example it returns unique elements of the array along axis - 0 and the return_counts arguements returns the array of number of time the element is present.

numpy.unique function is useful to obtain unique values from large dataset ignoring duplicates.

## Function 3 - numpy.arcsin , numpy.arccos, numpy.arctan

This function is used to find the angles of the elements in the array i.e. calulates the inverse of sine, cosine, tan.<br>
NOTE: The angle returned is in Radains format

In [15]:
# Example 1 

ary = np.array([0.30, 0.5, 0.75, 1, -1])
np.arcsin(ary)

array([ 0.30469265,  0.52359878,  0.84806208,  1.57079633, -1.57079633])

The above example gives the inverse of cosine of values present in the array in radians.

In [16]:
# Example 2 

np.arctan(ary)

array([ 0.29145679,  0.46364761,  0.64350111,  0.78539816, -0.78539816])

The above example gives the inverse of tan of values present in the array in radians.

In [17]:
# Example 3 

ary1 = np.array([1,-2,0.5,0.45])
np.arccos(ary1)

/tmp/ipykernel_37/2650276511.py:4: RuntimeWarning: invalid value encountered in arccos
  np.arccos(ary1)


array([0.        ,        nan, 1.04719755, 1.10403099])

In the above example one of the values is 2, but as we know cosine ranges from (-1,1). So the array values should range between -1 to 1.

The numpy.arcsin , numpy.arccos, numpy.arctan functions are useful to perform trigonometric operations on arrays.

## Function 4 - numpy.nanmax

This function returns the maximum value in the array ignoring the NaN(Not a Number - which can represent the missing values in the dataset).

In [19]:
# Example 1 - working

arry = np.array([[2.5, 4, 5, np.nan, 11],
                [np.nan, 1, 25, np.nan, 13],
                [24, 17, np.nan, np.nan, 13],
                [12, 5, 4, 1, 8 ]])
np.nanmax(arry, axis=0)

array([24., 17., 25.,  1., 13.])

The example shows the max value in the array along the axis - 0 ignoring NaNs.

In [20]:
# Example 2

np.nanmax(arry, axis = 1)

array([11., 25., 24., 12.])

The example shows the max value in the array along axis - 1 ignoring NaNs.

In [21]:
# Example 3 
np.nanmax(arry, axis = 3)

AxisError: axis 3 is out of bounds for array of dimension 2

We have a 2D array and it contains only two axis hence passing axis = 3 gives an error.

np.nanmax is very help to find a maximum value in large datasets ignoring the NaNs or missing values.

## Function 5 - numpy.isnan

Shows if the value in the array is NaN or not

In [23]:
# Example 1

x = np.array([[2.5, 4, 5, np.nan, 11],
                [np.nan, 1, 25, np.nan, 13],
                [24, 17, np.nan, np.nan, 13],
                [12, 5, 4, 1, 8 ]])
np.isnan(x)

array([[False, False, False,  True, False],
       [ True, False, False,  True, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

We passed array "x" as a parameter to isnan function which returned an array with datatype Bool showing whether the elements are NaN or not.

In [24]:
# Example 2
y = np.array([1, 2, 8, 7])
np.isnan(y)

array([False, False, False, False])

The function isnan returning an array with false as values shows that none of the elemwnts are NaN.

In [25]:
# Example 3 

np.isnan([2,42, 11])

array([False, False, False])

Array can be directly initialized and passed inside the isnan function.

The isnan function makes it easy to evaluate the data in the array by showing of it contains NaNs or not.

## Conclusion

We can see that numpy has various modules or functions which makes it easier to perform calucuations using arrays and evaluate them.
1. numpy.roll is useful in shifing the values of the array.
2. numpy.unique can be used to filter duplicates of the array.
3. numpy.arcsin , numpy.arccos, numpy.arctan provides the inverse of sine, cosine and tan.
4. numpy.nanmax is useful in finding the maximum value present in the array.
5. numpy.isnan is provides if data has NaN values.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* Numpy - w3schools : https://www.w3schools.com/python/numpy/numpy_intro.asp